# Mybatis相关配置文件
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/flowerstory
# Myabtis mapper文件。
mybatis:
  mapper-locations: classpath:mapper/*.xml

school:
  name: "哈哈"
  location: "北京"
  age: 18
